substitutions:
  _REGION: us-central1
  _REPOSITORY: codepop

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - codepop_backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - dashboard/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/dashboard:$SHORT_SHA
      - dashboard

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - codepop_backend/orbitdb/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orbitdb:$SHORT_SHA
      - codepop_backend/orbitdb

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/dashboard:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orbitdb:$SHORT_SHA
