# Generated by Django 5.1.2

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('Region', models.CharField(max_length=80)),
                ('City', models.CharField(max_length=80)),
                ('State', models.CharField(default='UT', max_length=40)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyHub',
            fields=[
                ('HubID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120, unique=True)),
                ('Region', models.CharField(max_length=80)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('MaxDeliveryRadiusMiles', models.PositiveIntegerField(default=1000)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('DrinkID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('SyrupsUsed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('SodaUsed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('AddIns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Price', models.FloatField()),
                ('Size', models.CharField(default='24oz', max_length=10)),
                ('Ice', models.CharField(default='regular', max_length=20)),
                ('User_Created', models.BooleanField()),
                ('Favorite', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('PreferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('Preference', models.CharField(max_length=100)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemType', models.CharField(choices=[('Soda', 'Soda'), ('Syrup', 'Syrup'), ('Add In', 'Add In'), ('Physical', 'Physical')], max_length=50)),
                ('Quantity', models.PositiveIntegerField()),
                ('ThresholdLevel', models.PositiveIntegerField()),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('HubID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='backend.supplyhub')),
                ('StoreID', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.store')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=500)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Type', models.CharField(max_length=50)),
                ('Global', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('PaymentStatus', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('remade', 'Remade')], default='pending', max_length=50)),
                ('PickupTime', models.DateTimeField(blank=True, null=True)),
                ('CreationTime', models.DateTimeField(auto_now_add=True)),
                ('LockerCombo', models.BigIntegerField(null=True)),
                ('StripeID', models.CharField(blank=True, max_length=255, null=True)),
                ('Drinks', models.ManyToManyField(to='backend.drink')),
                ('StoreID', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.store')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('RevenueID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField(default=1)),
                ('TotalAmount', models.FloatField(default=0.0)),
                ('SaleDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Refunded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('StockTransferID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemType', models.CharField(choices=[('Soda', 'Soda'), ('Syrup', 'Syrup'), ('Add In', 'Add In'), ('Physical', 'Physical')], max_length=50)),
                ('Quantity', models.PositiveIntegerField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('RequestedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('HubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='backend.supplyhub')),
                ('StoreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='backend.store')),
            ],
        ),
    ]
