# Generated by Django 5.1.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('AuditLogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=50)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemType', models.CharField(choices=[('Soda', 'Soda'), ('Syrup', 'Syrup'), ('Add In', 'Add In'), ('Physical', 'Physical')], max_length=50)),
                ('QuantityBefore', models.IntegerField()),
                ('QuantityAfter', models.IntegerField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('HubID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplyhub')),
                ('StoreID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.store')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
