# Generated by Django 5.1.2 on 2026-03-02 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_order_stripeid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('soda_dispenser', 'Soda Dispenser'), ('syrup_pump', 'Syrup Pump'), ('ice_maker', 'Ice Maker'), ('cooler', 'Cooler'), ('cleaning_system', 'Cleaning System')], max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('install_date', models.DateField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('repair-start', 'Repair Start'), ('repair-end', 'Repair End'), ('error', 'Error'), ('out-of-order', 'Out of Order'), ('schedule-service', 'Schedule Service')], default='normal', max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('status_change', 'Status Change'), ('repair', 'Repair'), ('routine_maintenance', 'Routine Maintenance'), ('inspection', 'Inspection')], max_length=20)),
                ('old_status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('warning', 'Warning'), ('repair-start', 'Repair Start'), ('repair-end', 'Repair End'), ('error', 'Error'), ('out-of-order', 'Out of Order'), ('schedule-service', 'Schedule Service')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('repair-start', 'Repair Start'), ('repair-end', 'Repair End'), ('error', 'Error'), ('out-of-order', 'Out of Order'), ('schedule-service', 'Schedule Service')], max_length=20)),
                ('description', models.TextField()),
                ('parts_replaced', models.JSONField(blank=True, null=True)),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('TransferID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('Quantity', models.PositiveIntegerField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('RequestedAt', models.DateTimeField(auto_now_add=True)),
                ('DeliveredAt', models.DateTimeField(blank=True, null=True)),
                ('EstimatedDelivery', models.DateTimeField()),
                ('Priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreID', models.AutoField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=100)),
                ('Region', models.CharField(choices=[('A', 'Region A - Chicago, IL'), ('B', 'Region B - Newark, NJ'), ('C', 'Region C - Logan, UT'), ('D', 'Region D - Dallas, TX'), ('E', 'Region E - Atlanta, GA'), ('F', 'Region F - Phoenix, AZ'), ('G', 'Region G - Boise, ID')], max_length=1)),
                ('Address', models.CharField(max_length=255)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('OperatingStatus', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='operational', max_length=20)),
                ('OpenedAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyHub',
            fields=[
                ('HubID', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(choices=[('A', 'Chicago, IL'), ('B', 'Newark, NJ'), ('C', 'Logan, UT'), ('D', 'Dallas, TX'), ('E', 'Atlanta, GA'), ('F', 'Phoenix, AZ'), ('G', 'Boise, ID')], max_length=1, unique=True)),
                ('LocationName', models.CharField(max_length=100)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('MaxCapacity', models.PositiveIntegerField()),
                ('CurrentLoad', models.PositiveIntegerField(default=0)),
                ('OperatingStatus', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('logistics_manager', 'Logistics Manager'), ('repair_staff', 'Repair Staff')], default='customer', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, help_text='Assigned region for logistics_manager role', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='LastRestockedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='UnitCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='PreferenceType',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='revenue',
            name='NetRevenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='OrderCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='PeriodEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='PeriodStart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='PeriodType',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='RefundAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='StripeID',
            field=models.CharField(),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('UserID', 'Preference'), name='unique_user_preference'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='backend.machine'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['Region'], name='idx_stores_region'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['OperatingStatus'], name='idx_stores_status'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='ToStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='backend.store'),
        ),
        migrations.AddField(
            model_name='machine',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machines', to='backend.store'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='StoreID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='backend.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='StoreID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='backend.store'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='StoreID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='backend.store'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['StoreID'], name='idx_inventory_store'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['ItemType'], name='idx_inventory_type'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['StoreID', 'ItemName'], name='idx_inventory_name_store'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='FromHub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='backend.supplyhub'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='backend.store'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['machine', '-created_at'], name='idx_maint_logs_machine'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['technician', '-created_at'], name='idx_maint_logs_tech'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['-created_at'], name='idx_maint_logs_created'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['store', 'status'], name='idx_machines_store_status'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['next_service_due'], name='idx_machines_service_due'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['ToStore'], name='idx_transfers_store'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['Status'], name='idx_transfers_status'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['-RequestedAt'], name='idx_transfers_requested'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='idx_userprofile_role'),
        ),
    ]
